### ISSUE TITLE
Empty notebooks

### ISSUE THREAD

**Issue by FabricioS** [g-haine/scrimp#1]
Dear Prof. Haine,
I have been reading the _Numerical approximation of port-Hamiltonian systems for hyperbolic or parabolic PDEs with boundary control_ with great interest.
Beyond the four notebooks available on Zenodo, I saw that there seems to be notebooks in the current repository but they appear to be empty. Would it be possible for you to restore them?

Best regards,
Fabrice Silva

**Comment by g-haine** [comment]
Unfortunately, we have to refactor the code from scratch the code.
We do not use FEniCS anymore and switch to GetFEM.

Bests.
